# Generated by Django 5.0.1 on 2024-02-18 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_image_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
