# Generated by Django 5.0.1 on 2024-02-18 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_remove_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
