# Generated by Django 5.0.1 on 2024-02-18 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
