# Generated by Django 5.0.1 on 2024-02-18 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0010_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
