# Generated by Django 5.0.1 on 2024-02-18 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0011_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
