# Generated by Django 5.0.1 on 2024-02-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0012_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
