# Generated by Django 5.0.1 on 2024-02-22 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0021_order_stutus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stutus',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
