# Generated by Django 5.0.1 on 2024-02-17 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maapp3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maapp3.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maapp3.post')),
            ],
        ),
    ]
